[build]
  publish = "AppCJ" # Ou apenas "." se você publicar a raiz do repositório
  command = "echo 'No build command needed for static HTML/CSS/JS'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
